import type { Playlist, Song } from '../types';
import { searchYouTubeMusic } from './youtubeSearch';

export interface SpotifyPlaylistMeta { id: string; name: string; description: string; imageUrl: string; total: number; externalUrl: string; }
export interface SpotifyImportedTrack { id: string; name: string; artist: string; album: string; imageUrl: string; externalUrl: string; }
const TOKEN_KEY = 'cineosync:spotify:token';
const REFRESH_KEY = 'cineosync:spotify:refresh';
const VERIFIER_KEY = 'cineosync:spotify:verifier';
const STATE_KEY = 'cineosync:spotify:state';
const clientId = () => (import.meta.env.VITE_SPOTIFY_CLIENT_ID || '').trim();
const redirectUri = () => (import.meta.env.VITE_SPOTIFY_REDIRECT_URI || window.location.origin).trim();
const base64Url = (bytes: ArrayBuffer) => btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
const randomString = (length: number) => { const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'; const bytes = crypto.getRandomValues(new Uint8Array(length)); return Array.from(bytes, (b) => chars[b % chars.length]).join(''); };
async function challenge(verifier: string) { return base64Url(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier))); }
export function extractSpotifyPlaylistId(value: string): string | null { const raw = value.trim(); if (/^[A-Za-z0-9]{22}$/.test(raw)) return raw; try { const url = new URL(raw); return url.pathname.match(/\/playlist\/([A-Za-z0-9]+)/i)?.[1] || null; } catch { return raw.match(/playlist[/:]([A-Za-z0-9]+)/i)?.[1] || null; } }
async function tokenRequest(body: URLSearchParams) { const response = await fetch('https://accounts.spotify.com/api/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error_description || data.error || `Spotify authentication failed (${response.status})`); return data; }
export function getSpotifyAccessToken() { try { return localStorage.getItem(TOKEN_KEY); } catch { return null; } }
export async function startSpotifyLogin() { const id = clientId(); if (!id) throw new Error('Spotify import needs VITE_SPOTIFY_CLIENT_ID.'); const verifier = randomString(64); const state = randomString(32); localStorage.setItem(VERIFIER_KEY, verifier); localStorage.setItem(STATE_KEY, state); const codeChallenge = await challenge(verifier); const url = new URL('https://accounts.spotify.com/authorize'); url.search = new URLSearchParams({ response_type: 'code', client_id: id, scope: 'playlist-read-private playlist-read-collaborative', redirect_uri: redirectUri(), state, code_challenge_method: 'S256', code_challenge: codeChallenge }).toString(); window.location.assign(url.toString()); }
export async function finishSpotifyLogin(): Promise<boolean> { const params = new URLSearchParams(window.location.search); const code = params.get('code'); if (!code) return false; const state = params.get('state'); const expected = localStorage.getItem(STATE_KEY); if (!state || !expected || state !== expected) throw new Error('Spotify login state validation failed.'); const verifier = localStorage.getItem(VERIFIER_KEY); const id = clientId(); if (!verifier || !id) throw new Error('Spotify login is not configured.'); const data = await tokenRequest(new URLSearchParams({ grant_type: 'authorization_code', code, redirect_uri: redirectUri(), client_id: id, code_verifier: verifier })); localStorage.setItem(TOKEN_KEY, data.access_token); if (data.refresh_token) localStorage.setItem(REFRESH_KEY, data.refresh_token); localStorage.removeItem(VERIFIER_KEY); localStorage.removeItem(STATE_KEY); const clean = new URL(window.location.href); ['code', 'state', 'error'].forEach((key) => clean.searchParams.delete(key)); window.history.replaceState({}, '', clean.toString()); return true; }
async function spotifyFetch(path: string) { let token = getSpotifyAccessToken(); if (!token) throw new Error('Connect Spotify before importing a playlist.'); let response = await fetch(`https://api.spotify.com/v1${path}`, { headers: { Authorization: `Bearer ${token}` } }); if (response.status === 401) { const refresh = localStorage.getItem(REFRESH_KEY); const id = clientId(); if (!refresh || !id) { localStorage.removeItem(TOKEN_KEY); throw new Error('Spotify authorization expired. Connect Spotify again.'); } try { const data = await tokenRequest(new URLSearchParams({ grant_type: 'refresh_token', refresh_token: refresh, client_id: id })); token = data.access_token; localStorage.setItem(TOKEN_KEY, token); if (data.refresh_token) localStorage.setItem(REFRESH_KEY, data.refresh_token); response = await fetch(`https://api.spotify.com/v1${path}`, { headers: { Authorization: `Bearer ${token}` } }); } catch { localStorage.removeItem(TOKEN_KEY); localStorage.removeItem(REFRESH_KEY); throw new Error('Spotify authorization expired. Connect Spotify again.'); } } const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error?.message || `Spotify request failed (${response.status})`); return data; }
export async function fetchSpotifyPlaylists(): Promise<SpotifyPlaylistMeta[]> { const playlists: SpotifyPlaylistMeta[] = []; let url = '/me/playlists?limit=50'; while (url) { const data = await spotifyFetch(url); for (const item of data.items || []) playlists.push({ id: item.id, name: item.name, description: item.description || '', imageUrl: item.images?.[0]?.url || '', total: item.items?.total || 0, externalUrl: item.external_urls?.spotify || `https://open.spotify.com/playlist/${item.id}` }); url = data.next ? data.next.replace('https://api.spotify.com/v1', '') : ''; } return playlists; }
export async function fetchSpotifyPlaylistTracks(playlistId: string): Promise<SpotifyImportedTrack[]> { const tracks: SpotifyImportedTrack[] = []; let url = `/playlists/${encodeURIComponent(playlistId)}/items?limit=50&market=IN`; while (url) { const data = await spotifyFetch(url); for (const item of data.items || []) { const track = item.item || item.track; if (!track || track.type !== 'track' || !track.name || !track.artists?.length) continue; tracks.push({ id: track.id, name: track.name, artist: track.artists.map((a: any) => a.name).join(', '), album: track.album?.name || '', imageUrl: track.album?.images?.[0]?.url || '', externalUrl: track.external_urls?.spotify || `https://open.spotify.com/track/${track.id}` }); } url = data.next ? data.next.replace('https://api.spotify.com/v1', '') : ''; } return tracks; }
export async function convertSpotifyTracksToPlayableSongs(tracks: SpotifyImportedTrack[], onProgress?: (done: number, total: number) => void): Promise<Song[]> { const output: Song[] = []; const queue = [...tracks]; let done = 0; const worker = async () => { while (queue.length) { const track = queue.shift(); if (!track) return; try { const result = await searchYouTubeMusic(`${track.artist} ${track.name} official audio`, 3); const match = result.songs.find((song) => song.youtubeVideoId); if (match) output.push({ ...match, title: track.name, artist: track.artist, album: track.album, coverArt: track.imageUrl || match.coverArt, tags: [...(match.tags || []), 'Spotify import'], sourceProvider: 'Spotify → YouTube' }); } catch {} done += 1; onProgress?.(done, tracks.length); } }; await Promise.all([worker(), worker(), worker(), worker()]); return output; }
export async function importSpotifyPlaylist(value: string, onProgress?: (done: number, total: number) => void): Promise<{ playlist: Playlist; songs: Song[] }> { const id = extractSpotifyPlaylistId(value); if (!id) throw new Error('Enter a valid Spotify playlist URL or playlist ID.'); const meta = (await fetchSpotifyPlaylists()).find((item) => item.id === id); const tracks = await fetchSpotifyPlaylistTracks(id); if (!tracks.length) throw new Error('Spotify returned no playable tracks for this playlist.'); const songs = await convertSpotifyTracksToPlayableSongs(tracks, onProgress); if (!songs.length) throw new Error('None of the Spotify tracks could be matched to playable YouTube videos.'); return { playlist: { id: `imported-spotify-${id}`, title: meta?.name || 'Imported Spotify Playlist', description: meta?.description || 'Imported from Spotify. Playback uses matching YouTube videos.', coverArt: meta?.imageUrl || songs[0].coverArt, songIds: songs.map((s) => s.id), mood: 'all', isCurated: false, creatorName: 'You', platformSource: 'Spotify → YouTube' }, songs }; }
export function disconnectSpotify() { [TOKEN_KEY, REFRESH_KEY, VERIFIER_KEY, STATE_KEY].forEach((key) => localStorage.removeItem(key)); }
