import React, { useMemo, useState } from 'react';
import { Clock3, Download, FolderDown, Heart, History, LibraryBig, MoreHorizontal, Play, Plus, Search, Trash2, Wifi, WifiOff } from 'lucide-react';
import { Song, Playlist, SupportedLanguage } from '../../types';
import { persistenceService } from '../../services/persistenceService';

interface LibraryViewProps { allSongs: Song[]; downloadedSongIds: Set<string>; likedSongIds: Set<string>; customPlaylists: Playlist[]; currentSong: Song|null; isPlaying: boolean; onPlaySong:(song:Song)=>void; onTogglePlay:()=>void; onToggleDownload:(song:Song)=>void; onToggleLike:(songId:string)=>void; isOfflineMode:boolean; onToggleOfflineMode:()=>void; onClearOfflineCache:()=>void; onSelectPlaylist:(pl:Playlist)=>void; onOpenImporter:()=>void; language:SupportedLanguage; }
type Section='overview'|'liked'|'history'|'downloads';

export const LibraryView:React.FC<LibraryViewProps>=({allSongs,downloadedSongIds,likedSongIds,customPlaylists,currentSong,isPlaying,onPlaySong,onToggleDownload,onToggleLike,isOfflineMode,onToggleOfflineMode,onClearOfflineCache,onSelectPlaylist,onOpenImporter})=>{
 const [section,setSection]=useState<Section>('overview'); const history=useMemo(()=>persistenceService.getHistory(30),[]); const liked=useMemo(()=>allSongs.filter(s=>likedSongIds.has(s.id)),[allSongs,likedSongIds]); const downloaded=useMemo(()=>allSongs.filter(s=>downloadedSongIds.has(s.id)),[allSongs,downloadedSongIds]);
 const visible=section==='liked'?liked:section==='history'?history.map(x=>x.song):section==='downloads'?downloaded:[];
 return <div className="cine-page cine-library-page">
  <section className="cine-library-head"><div><span className="cine-eyebrow">LIBRARY</span><h1>What you chose to keep.</h1><p>One place for liked tracks, listening history, imported playlists and the music you return to.</p></div><div className="cine-library-actions"><button onClick={onOpenImporter} className="cine-primary-action"><Plus size={15}/> Import playlist</button><button onClick={onToggleOfflineMode} className="cine-quiet-action">{isOfflineMode?<WifiOff size={15}/>:<Wifi size={15}/>} {isOfflineMode?'Offline on':'Offline mode'}</button></div></section>
  <section className="cine-library-statline"><button className={section==='overview'?'is-active':''} onClick={()=>setSection('overview')}><b>{customPlaylists.length}</b><span>Playlists</span></button><button className={section==='liked'?'is-active':''} onClick={()=>setSection('liked')}><b>{liked.length}</b><span>Liked</span></button><button className={section==='history'?'is-active':''} onClick={()=>setSection('history')}><b>{history.length}</b><span>History</span></button><button className={section==='downloads'?'is-active':''} onClick={()=>setSection('downloads')}><b>{downloaded.length}</b><span>Saved offline</span></button></section>
  {section==='overview'?<>
   <section className="cine-section"><div className="cine-section-head"><div><span className="cine-eyebrow">COLLECTIONS</span><h2>Your playlists</h2></div><span className="cine-section-note">{customPlaylists.length} collections</span></div>{customPlaylists.length?<div className="cine-playlist-grid cine-library-playlists">{customPlaylists.map(p=><button key={p.id} className="cine-playlist-card" onClick={()=>onSelectPlaylist(p)}><div className="cine-playlist-art"><img src={p.coverArt} alt="" referrerPolicy="no-referrer"/><span className="cine-playlist-play"><Play size={16} fill="currentColor"/></span></div><b>{p.title}</b><small>{p.songIds.length} tracks{p.platformSource?` · ${p.platformSource}`:''}</small></button>)}</div>:<div className="cine-empty-state"><LibraryBig size={18}/><div><b>Your library is ready for its first collection.</b><p>Import a real YouTube/Spotify playlist or create one from your listening.</p></div></div>}</section>
   <section className="cine-feature-row"><button className="cine-feature-card" onClick={()=>setSection('liked')}><span className="cine-feature-icon"><Heart size={18}/></span><span><small>LIKED MUSIC</small><b>Tracks you decided to keep.</b><em>{liked.length} saved in this account.</em></span><span>{liked.length}</span></button><button className="cine-feature-card" onClick={()=>setSection('history')}><span className="cine-feature-icon"><History size={18}/></span><span><small>LISTENING HISTORY</small><b>Pick up where you left off.</b><em>{history.length} recent listening events.</em></span><span>{history.length}</span></button><button className="cine-feature-card" onClick={()=>setSection('downloads')}><span className="cine-feature-icon"><Download size={18}/></span><span><small>OFFLINE</small><b>Keep your saved space tidy.</b><em>Downloads are local to this device.</em></span><span>{downloaded.length}</span></button></section>
  </>:<section className="cine-section"><div className="cine-section-head"><div><span className="cine-eyebrow">{section==='liked'?'LIKED MUSIC':section==='history'?'HISTORY':'OFFLINE'}</span><h2>{section==='liked'?'Songs you love':section==='history'?'Recently played':'Saved on this device'}</h2></div>{section==='downloads'&&downloaded.length>0&&<button className="cine-link-action" onClick={onClearOfflineCache}><Trash2 size={14}/> Clear all</button>}</div>{visible.length?<div className="cine-track-table">{visible.map((song,index)=>{const likedHere=likedSongIds.has(song.id);const saved=downloadedSongIds.has(song.id);const active=currentSong?.id===song.id&&isPlaying;return <div key={`${song.id}-${index}`} className={`cine-track-row ${active?'is-active':''}`}><span className="cine-track-index">{String(index+1).padStart(2,'0')}</span><button className="cine-track-art" onClick={()=>onPlaySong(song)}><img src={song.coverArt} alt="" referrerPolicy="no-referrer"/></button><button className="cine-track-main" onClick={()=>onPlaySong(song)}><b>{song.title}</b><small>{song.artist}{song.album?` · ${song.album}`:''}</small></button><button className={`cine-row-icon ${likedHere?'is-liked':''}`} onClick={()=>onToggleLike(song.id)}><Heart size={16} fill={likedHere?'currentColor':'none'}/></button>{section==='downloads'?<button className="cine-row-icon is-liked" onClick={()=>onToggleDownload(song)}><Trash2 size={15}/></button>:<button className={`cine-row-icon ${saved?'is-liked':''}`} onClick={()=>onToggleDownload(song)}><Download size={15}/></button>}</div>})}</div>:<div className="cine-empty-state"><span className="cine-empty-mark">00</span><div><b>Nothing here yet.</b><p>Play or save real music and this part of your library will fill naturally.</p></div></div>}</section>}
 </div>
};
export default LibraryView;
