import React, { useRef, useState } from 'react';
import { Camera, Check, ChevronRight, Globe2, LogOut, Music2, Palette, Settings2, Shield, Sliders, Sparkles, UserRound } from 'lucide-react';
import { UserProfile, AudioQuality, SupportedLanguage, AppTheme } from '../../types';

interface ProfileViewProps { profile:UserProfile; onUpdateProfile:(updated:Partial<UserProfile>)=>void; language:SupportedLanguage; onLanguageChange:(lang:SupportedLanguage)=>void; theme:AppTheme; onThemeChange:(theme:AppTheme)=>void; onOpenEqualizer:()=>void; }
const languages:[SupportedLanguage,string][]=[['en','English'],['hi','हिन्दी'],['ta','தமிழ்'],['te','తెలుగు'],['bn','বাংলা'],['mr','मराठी'],['pa','ਪੰਜਾਬੀ'],['gu','ગુજરાતી'],['kn','ಕನ್ನಡ'],['ml','മലയാളം'],['ur','اردو']];
const themes:[AppTheme,string][]=[['neon-obsidian','Obsidian'],['bollywood-ruby','Ruby'],['focus-emerald','Focus'],['sapphire-gym','Sapphire'],['chill-violet','Chill'],['glass-light','Light']];

export const ProfileView:React.FC<ProfileViewProps>=({profile,onUpdateProfile,language,onLanguageChange,theme,onThemeChange,onOpenEqualizer})=>{
 const [editing,setEditing]=useState(false);const [name,setName]=useState(profile.name);const [status,setStatus]=useState(profile.statusMessage);const inputRef=useRef<HTMLInputElement>(null);
 const save=()=>{onUpdateProfile({name:name.trim()||profile.name,statusMessage:status.trim()});setEditing(false)};
 const uploadAvatar=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>onUpdateProfile({avatar:String(reader.result||'')});reader.readAsDataURL(file)};
 return <div className="cine-page cine-profile-page">
  <section className="cine-profile-hero"><div className="cine-profile-avatar-wrap"><div className="cine-profile-avatar">{profile.avatar?<img src={profile.avatar} alt="Profile"/>:<span>{profile.name.slice(0,1).toUpperCase()||'C'}</span>}</div><label className="cine-avatar-edit"><Camera size={15}/><input ref={inputRef} type="file" accept="image/*" className="hidden" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label></div><div className="cine-profile-copy"><span className="cine-eyebrow">YOUR IDENTITY</span>{editing?<div className="cine-profile-edit"><input value={name} onChange={e=>setName(e.target.value)} autoFocus/><input value={status} onChange={e=>setStatus(e.target.value)}/><div><button onClick={save} className="cine-primary-action"><Check size={15}/> Save</button><button onClick={()=>setEditing(false)} className="cine-quiet-action">Cancel</button></div></div>:<><h1>{profile.name}</h1><p>@{profile.name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')||'cineosync'}</p><small>{profile.statusMessage||'Listening on Cineosync'}</small><button onClick={()=>setEditing(true)} className="cine-profile-edit-link">Edit profile</button></>}</div></section>
  <section className="cine-profile-stats"><div><b>{profile.stats.minutesListened}</b><span>minutes listened</span></div><div><b>{profile.stats.sessionsJoined}</b><span>sessions joined</span></div><div><b>{profile.stats.focusHours}</b><span>focus hours</span></div><div><b>{profile.stats.streakDays}</b><span>day streak</span></div></section>
  <section className="cine-section"><div className="cine-section-head"><div><span className="cine-eyebrow">PREFERENCES</span><h2>How Cineosync should feel.</h2></div></div><div className="cine-settings-grid">
   <div className="cine-setting"><div><span><Globe2 size={15}/> Language</span><small>Used for discovery and interface labels.</small></div><select value={language} onChange={e=>onLanguageChange(e.target.value as SupportedLanguage)}>{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></div>
   <div className="cine-setting"><div><span><Palette size={15}/> Atmosphere</span><small>Choose the visual environment.</small></div><select value={theme} onChange={e=>onThemeChange(e.target.value as AppTheme)}>{themes.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></div>
   <div className="cine-setting"><div><span><Sliders size={15}/> Audio quality</span><small>Playback preference for supported sources.</small></div><select value={profile.quality} onChange={e=>onUpdateProfile({quality:e.target.value as AudioQuality})}><option value="data-saver-64k">Data saver</option><option value="normal-128k">Normal</option><option value="high-320k">High</option></select></div>
   <button className="cine-setting cine-setting-button" onClick={onOpenEqualizer}><div><span><Settings2 size={15}/> Equalizer</span><small>Shape the sound for this device.</small></div><ChevronRight size={16}/></button>
  </div></section>
  <section className="cine-section"><div className="cine-section-head"><div><span className="cine-eyebrow">YOUR SOUND</span><h2>Musical identity</h2></div></div><div className="cine-identity-grid"><div><span>FAVORITE GENRES</span><b>{profile.favoriteGenres.length?profile.favoriteGenres.join(' · '):'Not set yet'}</b></div><div><span>PRESENCE</span><b>{profile.presenceMode.replace(/-/g,' ')}</b></div><div><span>DOWNLOAD POLICY</span><b>{profile.isWifiOnlyDownloads?'Wi‑Fi only':'Wi‑Fi + mobile data'}</b></div></div></section>
  <section className="cine-section"><div className="cine-section-head"><div><span className="cine-eyebrow">ACCOUNT</span><h2>Connected identity</h2></div></div><div className="cine-account-list"><div><span className="cine-account-icon"><Shield size={16}/></span><span><b>Authentication</b><small>Your account is managed through Cineosync authentication.</small></span><span className="cine-account-status">ACTIVE</span></div><div><span className="cine-account-icon"><Music2 size={16}/></span><span><b>Music services</b><small>Playlist imports and playable matches live in your library.</small></span><ChevronRight size={15}/></div><div><span className="cine-account-icon"><Sparkles size={16}/></span><span><b>Personalization</b><small>Recommendations adapt from your real activity.</small></span><ChevronRight size={15}/></div></div></section>
 </div>;
};
export default ProfileView;
