import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Users, Radio, Send, Sparkles, Link2, Check, Crown, Play, Pause, SkipForward, Plus, Music, MessageSquare, Wifi, LogOut, UserCog, Search, Loader2 } from 'lucide-react';
import { RoomState, Song, SupportedLanguage, ExperienceMode } from '../../types';
import { translations } from '../../data/translations';
import { wsClient } from '../../services/websocketClient';
import { searchYouTubeMusic } from '../../services/youtubeSearch';

interface SessionsViewProps { room: RoomState | null; currentSong: Song | null; isPlaying: boolean; onTogglePlay: () => void; onNextTrack: () => void; onSelectSong: (song: Song) => void; availableSongs: Song[]; currentUser: { id: string; name: string; avatar: string }; onCreateRoom: (customName: string, mood: string, isPrivate?: boolean) => void; onJoinRoom: (roomId: string) => void; onLeaveRoom: () => void; onOpenLyrics: () => void; language: SupportedLanguage; latencyMs: number; }
const button = 'inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 text-xs font-semibold text-zinc-200 transition hover:bg-white/10 active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-35';

export const SessionsView: React.FC<SessionsViewProps> = ({ room, currentSong, isPlaying, onTogglePlay, onNextTrack, onSelectSong, availableSongs, currentUser, onCreateRoom, onJoinRoom, onLeaveRoom, onOpenLyrics, language, latencyMs }) => {
  const t = translations[language] || translations.en;
  const [localRoom, setLocalRoom] = useState<RoomState | null>(room);
  const [localSong, setLocalSong] = useState<Song | null>(currentSong);
  const [localPlaying, setLocalPlaying] = useState(isPlaying);
  const [roomName, setRoomName] = useState(''); const [mood, setMood] = useState<ExperienceMode>('love'); const [isPrivate, setIsPrivate] = useState(false); const [joinCode, setJoinCode] = useState(''); const [chat, setChat] = useState(''); const [copied, setCopied] = useState(false);
  const [songSearch, setSongSearch] = useState(''); const [songResults, setSongResults] = useState<Song[]>([]); const [songSearching, setSongSearching] = useState(false); const [songSearchError, setSongSearchError] = useState('');
  const chatEnd = useRef<HTMLDivElement>(null); const effectiveRoom = localRoom || room; const effectiveSong = localSong || currentSong; const effectivePlaying = effectiveRoom ? localPlaying : isPlaying; const isHost = Boolean(effectiveRoom && effectiveRoom.hostId === currentUser.id);

  useEffect(() => setLocalRoom(room), [room]);
  useEffect(() => { if (currentSong) setLocalSong(currentSong); }, [currentSong]);
  useEffect(() => setLocalPlaying(isPlaying), [isPlaying]);
  useEffect(() => {
    const unsub = wsClient.addListener((event) => {
      if (event.type === 'ROOM_SYNC_STATE') { const next = event.payload as RoomState; if (next?.roomId) setLocalRoom(next); if (next?.currentSong) setLocalSong(next.currentSong); setLocalPlaying(Boolean(next?.isPlaying)); }
      else if (event.type === 'PARTICIPANT_JOINED' || event.type === 'PARTICIPANT_LEFT' || event.type === 'HOST_CHANGED') setLocalRoom((prev) => prev ? ({ ...prev, hostId: event.payload?.newHostId || event.payload?.hostId || prev.hostId, participants: event.payload?.participants || prev.participants, chatMessages: event.payload?.systemMessage ? [...prev.chatMessages, event.payload.systemMessage].slice(-80) : prev.chatMessages }) : prev);
      else if (event.type === 'RECEIVE_CHAT' || event.type === 'NEW_CHAT_MESSAGE') setLocalRoom((prev) => prev ? ({ ...prev, chatMessages: [...prev.chatMessages, event.payload].slice(-80) }) : prev);
      else if (event.type === 'PLAYBACK_SYNC') { if (event.payload?.song) setLocalSong(event.payload.song as Song); setLocalPlaying(Boolean(event.payload?.isPlaying)); }
    });
    const onRoomPlayback = (event: Event) => { const detail = (event as CustomEvent).detail; if (detail?.song) setLocalSong(detail.song as Song); setLocalPlaying(Boolean(detail?.isPlaying)); };
    window.addEventListener('syncbeat:room-playback', onRoomPlayback);
    return () => { unsub(); window.removeEventListener('syncbeat:room-playback', onRoomPlayback); };
  }, []);
  useEffect(() => { chatEnd.current?.scrollIntoView({ behavior: 'smooth' }); }, [effectiveRoom?.chatMessages.length]);
  useEffect(() => { const linkedRoom = new URLSearchParams(window.location.search).get('room'); if (linkedRoom && !effectiveRoom) { setJoinCode(linkedRoom); onJoinRoom(linkedRoom); } }, []);
  useEffect(() => {
    const q = songSearch.trim(); if (!q || !effectiveRoom || !isHost) { setSongResults([]); setSongSearchError(''); setSongSearching(false); return; }
    const controller = new AbortController(); const timer = window.setTimeout(async () => { setSongSearching(true); setSongSearchError(''); try { const result = await searchYouTubeMusic(q, 8); if (!controller.signal.aborted) setSongResults(result.songs); } catch (error: any) { if (!controller.signal.aborted) { setSongResults([]); setSongSearchError(error?.message || 'YouTube search failed.'); } } finally { if (!controller.signal.aborted) setSongSearching(false); } }, 350);
    return () => { controller.abort(); window.clearTimeout(timer); };
  }, [songSearch, effectiveRoom, isHost]);

  const create = (event: React.FormEvent) => { event.preventDefault(); const clean = roomName.trim(); if (!clean) return; onCreateRoom(clean, mood, isPrivate); setRoomName(''); };
  const join = () => { const value = joinCode.trim(); if (value) onJoinRoom(value); };
  const copyInvite = async () => { if (!effectiveRoom) return; try { await navigator.clipboard.writeText(`${window.location.origin}/?room=${encodeURIComponent(effectiveRoom.roomId)}`); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch {} };
  const sendChat = (event: React.FormEvent) => { event.preventDefault(); const text = chat.trim(); if (!text || !effectiveRoom) return; wsClient.sendChatMessage(text); setChat(''); };
  const selectHostSong = (song: Song) => { if (!isHost) return; onSelectSong(song); setSongSearch(''); setSongResults([]); };
  const nextHostSong = () => { if (!isHost || !effectiveRoom?.queue.length) return; const index = effectiveRoom.queue.indexOf(effectiveRoom.currentSongId || ''); const nextId = effectiveRoom.queue[(index + 1 + effectiveRoom.queue.length) % effectiveRoom.queue.length]; const nextSong = availableSongs.find((song) => song.id === nextId); if (nextSong) selectHostSong(nextSong); else onNextTrack(); };
  const queueSongs = useMemo(() => { const ids = new Set(effectiveRoom?.queue || []); return availableSongs.filter((song) => ids.has(song.id)); }, [availableSongs, effectiveRoom?.queue]);

  if (effectiveRoom) return <div className="space-y-5 pb-10">
    <section className="rounded-3xl border border-white/10 bg-gradient-to-br from-rose-950/40 via-zinc-950/80 to-purple-950/30 p-5 sm:p-7">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-rose-300"><span className="h-2 w-2 animate-pulse rounded-full bg-rose-400" /> LIVE SESSION <span className="font-mono text-zinc-500">{effectiveRoom.roomId}</span></div><h1 className="truncate text-2xl font-black tracking-tight text-white sm:text-3xl">{effectiveRoom.roomName}</h1><p className="mt-1 text-xs text-zinc-400">{effectiveRoom.participants.length} listener{effectiveRoom.participants.length === 1 ? '' : 's'} · <span className="text-emerald-400">{latencyMs}ms sync</span> · {isHost ? 'You are hosting' : `Hosted by ${effectiveRoom.participants.find((p) => p.id === effectiveRoom.hostId)?.name || 'another listener'}`}</p></div><div className="flex flex-wrap gap-2"><button className={button} onClick={copyInvite}>{copied ? <Check size={14} className="text-emerald-400" /> : <Link2 size={14} />}{copied ? 'Copied' : 'Invite link'}</button><button className={button} onClick={onLeaveRoom}><LogOut size={14} /> Leave</button></div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-2xl border border-white/10 bg-black/30 p-4">{effectiveSong ? <div className="flex flex-col gap-4 sm:flex-row sm:items-center"><img src={effectiveSong.coverArt} alt="" referrerPolicy="no-referrer" className="h-24 w-24 rounded-2xl object-cover ring-1 ring-white/10" /><div className="min-w-0 flex-1"><span className="text-[10px] font-bold uppercase tracking-widest text-rose-300">Now playing together</span><h2 className="mt-1 truncate text-lg font-bold text-white">{effectiveSong.title}</h2><p className="truncate text-sm text-zinc-400">{effectiveSong.artist}</p><button className="mt-3 text-xs font-semibold text-rose-300 hover:text-white" onClick={onOpenLyrics}>Open lyrics</button></div>{isHost && <div className="flex shrink-0 items-center gap-2"><button onClick={onTogglePlay} className="grid h-11 w-11 place-items-center rounded-full bg-white text-black shadow-xl" aria-label={effectivePlaying ? 'Pause session' : 'Play session'}>{effectivePlaying ? <Pause size={19} fill="currentColor" /> : <Play size={19} fill="currentColor" />}</button><button onClick={nextHostSong} className={button} aria-label="Next track"><SkipForward size={17} /></button></div>}</div> : <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center"><Music className="mx-auto mb-2 text-zinc-600" size={26} /><p className="text-sm font-semibold text-zinc-300">No track selected</p><p className="mt-1 text-xs text-zinc-500">Search a real YouTube track below to start listening together.</p></div>}</div>
        <div className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold text-white">Listeners</span><Wifi size={14} className="text-emerald-400" /></div><div className="space-y-2">{effectiveRoom.participants.map((p) => <div key={p.id} className="flex items-center gap-2 rounded-xl bg-white/[.04] p-2"><div className="grid h-8 w-8 shrink-0 place-items-center overflow-hidden rounded-full bg-white/10 text-xs font-bold text-white">{p.avatar ? <img src={p.avatar} alt="" className="h-full w-full object-cover" /> : p.name.slice(0, 1).toUpperCase()}</div><span className="min-w-0 flex-1 truncate text-xs font-semibold text-white">{p.name}{p.id === currentUser.id ? ' (You)' : ''}</span>{p.isHost ? <Crown size={13} className="text-amber-400" /> : isHost ? <button onClick={() => wsClient.transferHost(p.id)} className="text-zinc-400 hover:text-white" title="Transfer hosting"><UserCog size={13} /></button> : null}</div>)}</div></div></div>
    </section>

    <section className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold text-white"><Search size={16} className="text-rose-400" /> Search music without leaving the room</h2><span className="text-[10px] text-zinc-500">Host selects the shared track</span></div>{isHost ? <div className="relative"><Search size={15} className="absolute left-3 top-3 text-zinc-500" /><input value={songSearch} onChange={(e) => setSongSearch(e.target.value)} placeholder="Search YouTube for another song…" className="w-full rounded-xl border border-white/10 bg-black/30 py-2.5 pl-9 pr-10 text-xs text-white outline-none focus:border-rose-500/50" />{songSearching && <Loader2 size={15} className="absolute right-3 top-3 animate-spin text-rose-400" />}</div> : <p className="rounded-xl bg-black/20 p-3 text-xs text-zinc-500">Only the host can change the shared track. The room stays connected while the host searches.</p>}{songSearchError && <p className="mt-2 text-xs text-amber-300">{songSearchError}</p>}{isHost && songResults.length > 0 && <div className="mt-3 space-y-2">{songResults.map((song) => <button key={song.id} onClick={() => selectHostSong(song)} className="flex w-full items-center gap-3 rounded-xl border border-white/10 bg-black/20 p-2 text-left hover:bg-white/[.06]"><img src={song.coverArt} alt="" className="h-11 w-11 rounded-lg object-cover" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-white">{song.title}</span><span className="block truncate text-[10px] text-zinc-500">{song.artist}</span></span><Play size={15} className="shrink-0 text-rose-400" /></button>)}</div>}</section>

    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold text-white"><Music size={16} className="text-rose-400" /> Shared queue</h2><span className="text-[10px] text-zinc-500">{isHost ? 'You control playback' : 'Host controls playback'}</span></div>{queueSongs.length === 0 ? <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-xs text-zinc-500">Your shared queue will appear here.</div> : <div className="space-y-2">{queueSongs.map((song) => <div key={song.id} className="flex items-center gap-2 rounded-xl border border-white/5 bg-white/[.03] p-2"><img src={song.coverArt} alt="" className="h-10 w-10 shrink-0 rounded-lg object-cover" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-white">{song.title}</span><span className="block truncate text-[10px] text-zinc-500">{song.artist}</span></span>{isHost && <button onClick={() => selectHostSong(song)} className={button}><Play size={13} /> Play</button>}</div>)}</div>}</section>
      <section className="flex min-h-[430px] flex-col rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="mb-3 flex items-center gap-2 border-b border-white/10 pb-3"><MessageSquare size={16} className="text-purple-300" /><span className="text-sm font-bold text-white">Live chat</span></div><div className="min-h-0 flex-1 space-y-2 overflow-y-auto pr-1">{(effectiveRoom.chatMessages || []).map((message) => <div key={message.id} className="rounded-xl bg-white/[.05] p-2"><div className="mb-0.5 flex items-center gap-2"><span className="text-[10px] font-semibold text-zinc-300">{message.senderName}</span><span className="text-[9px] text-zinc-600">{new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div><p className="break-words text-xs text-white">{message.text}</p></div>)}<div ref={chatEnd} /></div><form onSubmit={sendChat} className="relative mt-3"><input value={chat} onChange={(e) => setChat(e.target.value)} placeholder="Say something…" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 pr-10 text-xs text-white outline-none focus:border-rose-500/50" /><button disabled={!chat.trim()} className="absolute right-1.5 top-1.5 grid h-7 w-7 place-items-center rounded-lg bg-rose-500 text-white disabled:opacity-30"><Send size={13} /></button></form></section></div>
  </div>;

  return <div className="space-y-6 pb-12"><section className="rounded-3xl border border-white/10 bg-gradient-to-br from-rose-950/40 via-zinc-950/80 to-purple-950/30 p-6 sm:p-8"><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-rose-500/20 bg-rose-500/10 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-rose-300"><Radio size={13} /> Listen together</div><h1 className="text-2xl font-black tracking-tight text-white sm:text-4xl">Create a real listening session.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-zinc-400">Share one link, stay in the room while searching, chat live, transfer hosting, and keep playback synchronized across joined devices.</p></section><div className="grid gap-5 lg:grid-cols-2"><form onSubmit={create} className="rounded-3xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><div className="mb-5"><h2 className="flex items-center gap-2 text-base font-bold text-white"><Sparkles size={17} className="text-rose-400" /> Create room</h2><p className="mt-1 text-xs text-zinc-500">Private rooms are accessible by invite link.</p></div><input value={roomName} onChange={(e) => setRoomName(e.target.value)} placeholder="Room name" className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-sm text-white outline-none focus:border-rose-500/50" /><div className="mt-3 flex gap-2"><select value={mood} onChange={(e) => setMood(e.target.value as ExperienceMode)} className="flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-xs text-white"><option value="love">Love</option><option value="focus">Focus</option><option value="gym">Gym</option><option value="friends">Friends</option><option value="chill">Chill</option></select><label className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-3 text-xs text-zinc-300"><input type="checkbox" checked={isPrivate} onChange={(e) => setIsPrivate(e.target.checked)} /> Private</label></div><button className="mt-4 w-full rounded-xl bg-rose-500 px-4 py-3 text-sm font-bold text-white hover:bg-rose-400">Create room</button></form><div className="rounded-3xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><div className="mb-5"><h2 className="flex items-center gap-2 text-base font-bold text-white"><Link2 size={17} className="text-purple-300" /> Join room</h2><p className="mt-1 text-xs text-zinc-500">Paste a room ID or the full invite URL.</p></div><input value={joinCode} onChange={(e) => setJoinCode(e.target.value)} placeholder="ROOM-XXXX or https://…?room=ROOM-XXXX" className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-sm text-white outline-none focus:border-purple-500/50" /><button onClick={join} className="mt-4 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold text-white hover:bg-white/10">Join room</button></div></div></div>;
};